import { SlashCommandBuilder, ChannelType, TextChannel, EmbedBuilder } from "discord.js"
import { getThemeColor } from "../functions";
import { SlashCommand } from "../types";
// Generated by https://quicktype.io

export interface SpaceImgSchema {
    copyright:       string;
    date:            string;
    explanation:     string;
    hdurl:           string;
    media_type:      string;
    service_version: string;
    title:           string;
    url:             string;
}

const command : SlashCommand = {
    command: new SlashCommandBuilder()
    .setName("spaceimg")
    .setDescription("get an image directly from above us!")
    ,
    execute: async interaction => {
        const req = await fetch("https://api.nasa.gov/planetary/apod?api_key="+process.env.NASA_API_KEY);
        const res:SpaceImgSchema = await req.json();
        interaction.reply({
            embeds: [
                new EmbedBuilder()
                .setAuthor({name:res.copyright})
                .setTitle(res.title)
                .setDescription(res.explanation)
                .setFooter({text:"Shot at "+res.date})
                .setImage(res.hdurl)
            ]
        })
    },
    cooldown: 10
}

export default command